openprocurement/robot_tests

- op_robot_tests/tests_files/brokers/openprocurement_client_helper.py
- op_robot_tests/tests_files/etender_service.py
- op_robot_tests/tests_files/singleItemTender.robot
- op_robot_tests/tests_files/singleItemTenderComplaints.robot
- setup.py
Two test cases were moved into singleItemTenderComplaints and one was already there.
Four more were dropped since they are same as first two.
> Move complaint tests from singleItemTender into singleItemTenderComplaints; improve PEP8 compliance

- buildout.cfg
- op_robot_tests/tests_files/service_keywords.py
This is mainly needed to get a well-readable log of Robot Framework tests.
> Prettify representation of Munches

- buildout.cfg
The first commit saves a lot of time, disk space and network traffic by fetching dependencies as eggs and source distributions instead of cloning their Git repositories. Changes in openprocurement_client happen quite frequently, so it remained intact.
The second commit contains a small fix for #22.
> Stop fetching dependencies from Git; fix #22

- op_robot_tests/tests_files/brokers/openprocurement_client.robot
- op_robot_tests/tests_files/contract.robot
- op_robot_tests/tests_files/keywords.robot
- op_robot_tests/tests_files/qualification.robot
Для запуску потребує `arctifact.yaml` у op_robot_tests/tests_files/datа.
`tender test -> (auction) ->  qualification test -> contract test`
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/73)
> Add qualification and contract tests

- op_robot_tests/tests_files/initial_data.py
- op_robot_tests/tests_files/singleItemTender.robot
This field must be clearly specified, that was bug in its absence
Also rewrite "true" -> True in initial_data.py, it also was bug
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/115)
> Add valueAddedTaxIncluded to test_tender_data

- op_robot_tests/tests_files/meatTender.robot
- op_robot_tests/tests_files/multiItemTender.robot
- op_robot_tests/tests_files/multiLotTender.robot
- op_robot_tests/tests_files/openEU.robot
- op_robot_tests/tests_files/openUA.robot
- op_robot_tests/tests_files/singleItemTender.robot
From initial_data=${tender_data} to initial_data=${adapted_data}
It was copy-paste error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/143)
> Fix caching initial tender data

- op_robot_tests/tests_files/initial_data.py
Because broker DZO can't display so many digits
This must be changed back in few months
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/185)
> Change max value of tender.value.amount

- op_robot_tests/tests_files/op_faker/op_faker_data.json
Because checking display of this fields was failing for DZO and privatmarker
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/201)
> Delete useless spaces from op_faker_data.json

- op_robot_tests/tests_files/keywords.robot
Because it is replaced with `Run as` everywhere
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/219)
> Delete `Викликати для учасника` from keywords.robot

- op_robot_tests/tests_files/initial_data.py
- op_robot_tests/tests_files/service_keywords.py
Зміни пов'язані з перейменуванням типу процедури для  конкурентного діалогу
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/241)
> Rename procurementMethodType for competitiveDialogue

- op_robot_tests/tests_files/brokers/openprocurement_client.robot
- op_robot_tests/tests_files/keywords.robot
- op_robot_tests/tests_files/singleItemAuction.robot
Now it calls `Підготувати дані для оголошення тендера` for each user in
test. Also `Підготувати дані для оголошення тендера` now have additional
``${role_name}`` argument in order to have possibility to update different
data depending on that argument.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/256)
> Remake `Адаптувати дані для оголошення тендера`

- op_robot_tests/tests_files/aboveThreshold_keywords.robot
- op_robot_tests/tests_files/base_keywords.robot
- op_robot_tests/tests_files/brokers/openprocurement_client.robot
- op_robot_tests/tests_files/brokers/openprocurement_client_helper.py
- op_robot_tests/tests_files/initial_data.py
- op_robot_tests/tests_files/keywords.robot
- op_robot_tests/tests_files/openProcedure.robot
- op_robot_tests/tests_files/qualification.robot
- op_robot_tests/tests_files/service_keywords.py
Main things are to use `${doc_id}` instead of `${url}` to find proper document and to remove file after uploading.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/259)
> Remake document's display checking test cases

- op_robot_tests/tests_files/brokers/openprocurement_client_helper.py
Retry only requests with 5xx and 429 status codes or requests which throw BadStatusLine exception.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/282)
> Rewrite `retry_if_request_failed`

- op_robot_tests/tests_files/keywords.robot
None is added to update LMD not in teardown section.
About empty - i dont know what it is doing here. Maybe there are some workarounds,
so i left it as it was.
Thx to @OSerhii for thix fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/292)
> Add checking for none value

- op_robot_tests/tests_files/aboveThreshold_keywords.robot
- op_robot_tests/tests_files/base_keywords.robot
- op_robot_tests/tests_files/brokers/openprocurement_client.robot
- op_robot_tests/tests_files/brokers/openprocurement_client_helper.py
Cannot merge this, coz it's not working. There is must to have access token in get_tender() arguments from client.py.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/319)
> Use artificial id instead of internal in work with bid documents

- op_robot_tests/tests_files/keywords.robot
- op_robot_tests/tests_files/service_keywords.py
Parameters defined in brokers.yaml and users.yaml can be overridden
through command line. Example of usage:
```json
-v BROKERS_PARAMS:'{"Quinta": {"intervals": {"default": {"enquiry": [0, 0], "tender": [0, 5.3]}}}}'
-v USERS_PARAMS:'{"users": {"Tender_Owner": {"api_key": "a"}}}'
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/454)
> Implement parameters passing through command line

- op_robot_tests/tests_files/initial_data.py
- op_robot_tests/tests_files/keywords.robot
- op_robot_tests/tests_files/service_keywords.py
This variable can be specified as a command line argument, e.g. `-v submissionMethodDetails:"quick"`. Currently supported values are listed [here](http://api-docs.openprocurement.org/en/latest/acceleration.html). If the variable is not set, the `submissionMethodDetails` field of the initial tender data falls back to its default value – `quick`. 
```bash
bin/op_tests -s openProcedure -A robot_tests_arguments/single_item_tender.txt -v submissionMethodDetails:"quick(mode:no-auction)"
```
```bash
bin/op_tests -s openProcedure -A robot_tests_arguments/single_item_tender.txt -v submissionMethodDetails:"quick(mode:fast-forward)"
```
```bash
bin/op_tests -s openProcedure -A robot_tests_arguments/openua_testing.txt -v submissionMethodDetails:"quick(mode:fast-forward)"
```
```bash
bin/op_tests -s …
```
> New variable for submissionMethodDetails

- op_robot_tests/tests_files/initial_data.py
- op_robot_tests/tests_files/openProcedure.robot
- op_robot_tests/tests_files/service_keywords.py
For bid_value_amount, the value that's equal to max_value_amount or greater than max_value_amount+minimalStep has been generated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/458)
> Change bid_value_amount

- op_robot_tests/tests_files/brokers/openprocurement_client_helper.py
Судячі з логів, помилка виникала при здійснені великої кількості запитів до ЄДР API, використовуючи 1 ключ. Додали sleep, у випадку коли отримуємо 429 Too many requests від ЄДР API.
[issue](https://github.com/openprocurement/robot_tests/issues/531)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/538)
> Add sleep for 429

- op_robot_tests/tests_files/data/brokers.yaml
Изменение параметров запуска тестировщика во избежание ошибок, связанных с задержками публикации аукционов на площадке.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/558)
> Изменение таймеров для трех площадок - uisce, zupb, ukin

- op_robot_tests/tests_files/base_keywords.robot
- op_robot_tests/tests_files/brokers/openprocurement_client.robot
- op_robot_tests/tests_files/complaints.robot
AboveThreshold procedure can be specified as a command line argument _**-v MODE:openua**_
Test cases marked with below_complaint tag should be excluded using the argument _**-e below_complaint**_.
Run command:
**bin/op_tests -s complaints -v MODE:openua -e below_complaint -v submissionMethodDetails:"quick(mode:fast-forward)"**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/525)
> OpenUA complaints

- op_robot_tests/tests_files/keywords.robot
This change adjusts the test suite behaviour to comply with the replanning of `tenderPeriod.endDate` on `dgfInsider` procedures.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/702)
> Update "Дочекатись дати закінчення прийому пропозицій" for dgfInsider

- buildout.cfg
- op_robot_tests/tests_files/aboveThreshold_keywords.robot
- op_robot_tests/tests_files/base_keywords.robot
- op_robot_tests/tests_files/brokers/openprocurement_client.robot
- op_robot_tests/tests_files/contract_signing.robot
- op_robot_tests/tests_files/data/brokers.yaml
- op_robot_tests/tests_files/initial_data.py
- op_robot_tests/tests_files/keywords.robot
- op_robot_tests/tests_files/openProcedure.robot
- op_robot_tests/tests_files/qualification.robot
- op_robot_tests/tests_files/resource.robot
- op_robot_tests/tests_files/service_keywords.py
- robot_tests_arguments/esco_meat_one_lot_budget.txt
- robot_tests_arguments/esco_multilot_other.txt
- robot_tests_arguments/esco_no_lots_other.txt
Currently auctions are skipped in the esco scenarios, thus the no-auction mode should be set with a command line argument: -v submissionMethodDetails:"quick(mode:no-auction)". Otherwise the default value submissionMethodDetails:"quick" will be set.
Since there are no auctions, it is necessary to exclude the auction_url tag with a command line argument: -e auction_url.
Thus, the openProcedure test suite will be run with the command:
bin/op_tests -s openProcedure -A robot_tests_arguments/(name of the argument file) -e auction_url -v submissionMethodDetails:"quick(mode:no-auction)"
For details on esco scenarios description see: https://docs.google.com/a/quintagroup.com/document/d/1ML_-lD_McXMJd9bQYCZS8E4z03LEaS6Nxhh6PEdMzww/edit?usp=sharing
This change is [<img …
> Three new esco scenarios
