op_robot_tests/tests_files/brokers/prom.robot
=> minor fixes

.gitignore, README.md, bootstrap.py, buildout.cfg, ez_setup.py
Source: https://github.com/openprocurement/openprocurement.robottests.buildout
=> Merge openprocurement.robottests.buildout

.gitignore, op_robot_tests/tests_files/brokers/etender.robot, op_robot_tests/tests_files/brokers/netcast.robot, op_robot_tests/tests_files/brokers/newtend.robot, op_robot_tests/tests_files/brokers/publicbid.robot, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml, op_robot_tests/tests_files/documents/TestDocument.docx, op_robot_tests/tests_files/etender_service.py, op_robot_tests/tests_files/service_keywords.py
Includes everything from #11, updated to match the current state of `master`.
Some parts that should not be modified (e.g. `initial_data.py`, `single-` and `multiItemTender.robot`, `openprocurement_client.robot`, `keywords.robot`) were not included.
Also includes a few fixes for `etender.robot` and a minor change for `.gitignore`.
=> Actualize and merge branch 'w-be/master'

op_robot_tests/tests_files/brokers/newtend.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/brokers/prom.robot, op_robot_tests/tests_files/brokers/publicbid.robot, op_robot_tests/tests_files/brokers/smarttender.robot, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/multiItemTender.robot, op_robot_tests/tests_files/singleItemTender.robot, op_robot_tests/tests_files/singleItemTenderComplaints.robot
This change introduces an ability to select current broker and role independently.
=> Improve mechanism of broker and role selection; minor changes in formatting

README.md, op_robot_tests/tests_files/brokers/etender.robot, op_robot_tests/tests_files/brokers/newtend_service.py, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/local_time.py, op_robot_tests/tests_files/multiItemTender.robot, op_robot_tests/tests_files/service_keywords.py, op_robot_tests/tests_files/singleItemTender.robot, op_robot_tests/tests_files/singleItemTenderComplaints.robot
Also includes various fixes and small changes.
=> Use get_now where possible

buildout.cfg, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/meatTender.robot, op_robot_tests/tests_files/multiItemTender.robot, op_robot_tests/tests_files/multiLotTender.robot, op_robot_tests/tests_files/resource.robot, op_robot_tests/tests_files/service_keywords.py, setup.py
Також включає виправлення помилок:
- дублювання одинакових предметів закупівлі 
- відсутність лапок у auction_bid
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/28)
=> Add tests for MEAT and multilot tenders

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
=> SmartTender settings

op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/meatTender.robot, op_robot_tests/tests_files/multiLotTender.robot, op_robot_tests/tests_files/service_keywords.py, op_robot_tests/tests_files/singleItemTender.robot
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/54)
=> Upd bid operations

op_robot_tests/tests_files/service_keywords.py
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/56)
=> Fix create_data_dict for work with list

op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/meatTender.robot, op_robot_tests/tests_files/multiItemTender.robot, op_robot_tests/tests_files/multiLotTender.robot, op_robot_tests/tests_files/singleItemTender.robot, op_robot_tests/tests_files/singleItemTenderComplaints.robot
1. Оновив теги у 
- multiItemTender
- meatTender 
- multiLotTender
2. Добавив `critical level `  для
- singleItemTender
- multiItemTender
3. Добавив `minimal` для
- multiItemTender
4.  Добавив документацію для тестів, що використовують shouldfail для
- meatTender 
- multiLotTender
5.  Добавив  `[Setup]  Дочекатись синхронізації з майданчиком` при зміні ролі для усіх чотирьох вищезгаданих тестів.
6.  Оптимізація використання даних у initial_data
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/52)
=> Add tags, documentation and setup

op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/openUA.robot, op_robot_tests/tests_files/service_keywords.py
api_version:0.12
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/46)
=> Add test for openua tenders

op_robot_tests/tests_files/data/users.yaml
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/59)
=> E-tender: Change homepage in users.yaml

op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/meatTender.robot, op_robot_tests/tests_files/multiLotTender.robot, op_robot_tests/tests_files/openUA.robot, op_robot_tests/tests_files/singleItemTender.robot
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/61)
=> Update keyword "Змінити цінову пропозицію"

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/57)
=> Prom: some fix brokers, users, resource

op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/limited.robot, op_robot_tests/tests_files/meatTender.robot, op_robot_tests/tests_files/multiItemTender.robot, op_robot_tests/tests_files/multiLotTender.robot, op_robot_tests/tests_files/openUA.robot, op_robot_tests/tests_files/singleItemTender.robot
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/60)
=> Prepare start tender data

op_robot_tests/tests_files/brokers/openprocurement_client.robot
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/65)
=> Fix argument name error

op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/openEU.robot, op_robot_tests/tests_files/service_keywords.py
Використовує зміни до op.client.python [PL#22](https://github.com/openprocurement/openprocurement.client.python/pull/22)
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/66)
=> Add openEU procedure test

op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/singleItemTender.robot
Fix [singleitemtender](http://testing.openprocurement.org/job/rt_baseline/TEST_SUITE=singleItemTender/) and [multilottender](http://testing.openprocurement.org/job/rt_baseline_multilot/TEST_SUITE=multiLotTender/) errors
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/67)
=> Fix question errors

op_robot_tests/tests_files/initial_data.py
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/70)
=> fake integer in bid for multilot

op_robot_tests/tests_files/multiLotTender.robot
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/71)
=> Fix 'provider' tag in multiLotTender

op_robot_tests/tests_files/auction.robot, op_robot_tests/tests_files/contract.robot, op_robot_tests/tests_files/qualification.robot
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/75)
=> Add auction test

op_robot_tests/tests_files/keywords.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/76)
=> Dump tender internal id

op_robot_tests/tests_files/keywords.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/77)
=> Dump last modification date

op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/openEU.robot, op_robot_tests/tests_files/openUA.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/80)
=> openUA openEU complaints

op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/service_keywords.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/79)
=> Upd create artifact

op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/service_keywords.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/82)
=> Add ignore error

op_robot_tests/tests_files/auction.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/83)
=> Auction time

op_robot_tests/tests_files/qualification.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/84)
=> Delete check suppliers legal name

op_robot_tests/tests_files/contract.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/87)
=> Wait stand-still period

op_robot_tests/tests_files/singleItemTenderComplaints.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/88)
=> Add setup to 'Відображення заголовку вимоги для глядача'

op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/limited_keywords.robot, op_robot_tests/tests_files/meatTender.robot, op_robot_tests/tests_files/multiItemTender.robot, op_robot_tests/tests_files/multiLotTender.robot, op_robot_tests/tests_files/negotiation.quick.robot, op_robot_tests/tests_files/negotiation.robot, op_robot_tests/tests_files/openEU.robot, op_robot_tests/tests_files/openUA.robot, op_robot_tests/tests_files/reporting.robot, op_robot_tests/tests_files/singleItemTender.robot, op_robot_tests/tests_files/singleItemTenderComplaints.robot
Ready to merge
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/90)
=> Add test teardown

op_robot_tests/tests_files/multiLotTender.robot, op_robot_tests/tests_files/singleItemTender.robot
Ще не відтестовно.
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/85)
=> Require failure for bids check

op_robot_tests/tests_files/auction.robot, op_robot_tests/tests_files/contract.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/91)
=> Add update last modification date

op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/keywords.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/92)
=> Move LAST_REFRESH_DATE initialization to keywords.robot

op_robot_tests/tests_files/multiLotTender.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/96)
=> Correct test suits titles

op_robot_tests/tests_files/brokers/plan_client.robot, op_robot_tests/tests_files/brokers/plan_client_helper.py, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml, op_robot_tests/tests_files/initial_plan_data.py, op_robot_tests/tests_files/keywords_plan.robot, op_robot_tests/tests_files/meatPlan.robot, op_robot_tests/tests_files/plan.robot, op_robot_tests/tests_files/service_plan_keywords.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/97)
=> Plan workflow to 2.0.x

op_robot_tests/tests_files/singleItemTender.robot
When passing string as argument to `Should be true` keyword,
it must be quoted
http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Should%20Be%20True
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/100)
=> Change ${url} -> '${url}'

op_robot_tests/tests_files/singleItemTender.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/104)
=> Code style improvement

op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/limited_keywords.robot
Rewrite documentation to `Дочекатись синхронізації з майданчиком`
Replace spaces in `Set To Dictionary` and `Create Dictionary` to `=`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/102)
=> Update synchronisation time formula

op_robot_tests/tests_files/keywords.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/103)
=> Log git info

op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/brokers/openprocurement_client_helper.py
Adds support for new feature of openprocurement.client.python.
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/98)
=> Add get tender id by uaid

op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/multiLotTender.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/101)
=> Update initial data

op_robot_tests/tests_files/data/users.yaml
Change
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/106)
=> E-tender: Change users.yaml

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
SmartTender. New settings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/107)
=> SmartTender: New settings

op_robot_tests/tests_files/brokers/openprocurement_client.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/112)
=> Rename `Дискваліфікація` → `Дискваліфікувати`

op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/limited_keywords.robot
Ready to merge
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/94)
=> Work with Створити тендер... (adapted_data)

op_robot_tests/tests_files/initial_data.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/99)
=> Descriptions with id

op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/keywords.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/108)
=> Work with cache on keywords level

op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/service_keywords.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/113)
=> Add `Порівняти системний і серверний час`

op_robot_tests/tests_files/data/users.yaml
Изменен параметр homepage для пользователей PrivatMarket в users.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/117)
=> PrivatMarket: change privat_market URL

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/118)
=> DZO: changed DZO actors data and DZO intervals

op_robot_tests/tests_files/contract.robot, op_robot_tests/tests_files/openEU.robot, op_robot_tests/tests_files/openUA.robot, op_robot_tests/tests_files/qualification.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/114)
=> Simplify :FOR loops

op_robot_tests/tests_files/auction.robot, op_robot_tests/tests_files/contract.robot, op_robot_tests/tests_files/meatTender.robot, op_robot_tests/tests_files/openEU.robot, op_robot_tests/tests_files/qualification.robot
Не змінив лиш Require Failure у [singleItemTender](https://github.com/openprocurement/robot_tests/blob/3ad9b7c4823e65a2c76050849327a0133dbe5b4f/op_robot_tests/tests_files/singleItemTender.robot#L533)
[multiLotTender](https://github.com/openprocurement/robot_tests/blob/6e97cb227ce3667d89a00572be320f90cbd6e869/op_robot_tests/tests_files/multiLotTender.robot#L381) з причини непотрібності перевірки цих існування цих даних у кеші.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/119)
=> Отримати дані із тендера

op_robot_tests/tests_files/initial_data.py
In test_tender_data_limited
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/126)
=> Make description fields unicode string

op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/limited_keywords.robot, op_robot_tests/tests_files/meatTender.robot, op_robot_tests/tests_files/multiItemTender.robot, op_robot_tests/tests_files/multiLotTender.robot, op_robot_tests/tests_files/openEU.robot, op_robot_tests/tests_files/openUA.robot, op_robot_tests/tests_files/singleItemTender.robot, op_robot_tests/tests_files/singleItemTenderComplaints.robot
В цьому пр до всіх сценаріїв додається адаптація початкових даних для створення тендера під роль ${tender_owner}`а.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/120)
=> Adapted intial data

op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/multiLotTender.robot, op_robot_tests/tests_files/service_keywords.py, op_robot_tests/tests_files/singleItemTender.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/125)
=> Work with question id

op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/openEU.robot, op_robot_tests/tests_files/openUA.robot
Add `Дочекатись дати початку періоду уточнень` to keywords.robot, openUA.robot and openEU.robot
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/132)
=> Wait to start of enquiry period

op_robot_tests/tests_files/brokers/openprocurement_client.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/139)
=> SingleLot bid

op_robot_tests/tests_files/brokers/openprocurement_client.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/140)
=> Single lot auction url

op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/meatTender.robot, op_robot_tests/tests_files/multiItemTender.robot, op_robot_tests/tests_files/multiLotTender.robot, op_robot_tests/tests_files/openEU.robot, op_robot_tests/tests_files/openUA.robot, op_robot_tests/tests_files/singleItemTender.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/146)
=> Single lot bid and caching fixes

op_robot_tests/tests_files/meatTender.robot, op_robot_tests/tests_files/multiItemTender.robot, op_robot_tests/tests_files/multiLotTender.robot, op_robot_tests/tests_files/openEU.robot, op_robot_tests/tests_files/openUA.robot, op_robot_tests/tests_files/singleItemTender.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/142)
=> Fix cached tender initial data in singleItemTender

op_robot_tests/tests_files/openEU.robot, op_robot_tests/tests_files/openUA.robot
Дочекатись дати початку періоду уточнень -> Дочекатись дати початку прийому пропозицій
Оскільки в initial_data enquiryPeriod для відкритих процедур немає.
Дякую @OSerhii
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/136)
=> Fix `Дочекатись дати початку *` in open* procedures

op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/multiItemTender.robot, op_robot_tests/tests_files/service_keywords.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/134)
=> Create and delete items by item id

op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/service_keywords.py
Also amend documentation to `Підтвердити постачальника` keyword
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/158)
=> Clear service_keywords.py from outdated functions

op_robot_tests/tests_files/auction.robot, op_robot_tests/tests_files/data/users.yaml, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/meatTender.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/156)
=> Meat auction

op_robot_tests/tests_files/resource.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/162)
=> Update api version in resource.robot

op_robot_tests/tests_files/auction.robot
Supersedes #63.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/122)
=> Add implementation of waiting for the end of the auction

op_robot_tests/tests_files/singleItemTender.robot
Уніфіковано теги в singleItemTender
Переіменовано тест кейси в singleItem (оголошеного тендера -> однопредметного тендера)
Ready to merge, but who will merge? :(
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/130)
=> Unify single item tags and test names

op_robot_tests/tests_files/auction.robot, op_robot_tests/tests_files/contract.robot, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/meatTender.robot, op_robot_tests/tests_files/multiItemTender.robot, op_robot_tests/tests_files/multiLotTender.robot, op_robot_tests/tests_files/negotiation.quick.robot, op_robot_tests/tests_files/negotiation.robot, op_robot_tests/tests_files/openEU.robot, op_robot_tests/tests_files/openUA.robot, op_robot_tests/tests_files/qualification.robot, op_robot_tests/tests_files/reporting.robot, op_robot_tests/tests_files/resource.robot, op_robot_tests/tests_files/service_keywords.py, op_robot_tests/tests_files/singleItemTender.robot, op_robot_tests/tests_files/singleItemTenderComplaints.robot
Ref (comments): b512814 d0b22f6 9b702d2 9a1de79
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/133)
=> Optimal intervals

op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/service_keywords.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/151)
=> Del auction_bid and set_tender_periods

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/152)
=> Newtend: fix access Newtend_Viewer; fix newtend broker timeout

op_robot_tests/tests_files/initial_data.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/149)
=> Fix minimalStep.amount

op_robot_tests/tests_files/keywords.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/153)
=> Add status, diff and reflog to "Залогувати git-дані"

op_robot_tests/tests_files/multiItemTender.robot, op_robot_tests/tests_files/service_keywords.py
Вирішення проблеми з відсутністю даних про item у кеші tender_ownera при видалення предмету закупівлі.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/167)
=> Fix multi item

op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/limited_keywords.robot, op_robot_tests/tests_files/multiItemTender.robot, op_robot_tests/tests_files/service_keywords.py, op_robot_tests/tests_files/singleItemTender.robot
In order to have possibility to compare dates with accuracy passed in
human-readable format
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/129)
=> Update time comparison

op_robot_tests/tests_files/limited_keywords.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/168)
=> Delete unnecessary dot in dict path

op_robot_tests/tests_files/auction.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/contract.robot, op_robot_tests/tests_files/data/users.yaml, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/qualification.robot
Перенесення у гілку devel [#147](https://github.com/openprocurement/robot_tests/pull/147)
_____
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/160)
=> Lot auction, qualification and contract

buildout.cfg, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/170)
=> Adding proztorg broker

op_robot_tests/runner.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/175)
=> Add --loglevel trace:info to standard command args

op_robot_tests/tests_files/keywords.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/176)
=> Add `Log  ${status}` to `Залогувати git-дані`

op_robot_tests/tests_files/multiLotTender.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/186)
=> Add necessary argument to keyword in multiLotTender

op_robot_tests/tests_files/op_faker.py
Delete unused units field
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/187)
=> Update faker errors related to flake8 requirements

op_robot_tests/tests_files/aboveThreshold.robot, op_robot_tests/tests_files/aboveThreshold_keywords.robot, op_robot_tests/tests_files/auction.robot, op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/belowThreshold.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/service_keywords.py, op_robot_tests/tests_files/singleItemTenderComplaints.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/188)
=> Base keywords

op_robot_tests/tests_files/aboveThreshold_keywords.robot, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/openProcedure.robot
And add new tags.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/189)
=> Open Procedure test

op_robot_tests/tests_files/service_keywords.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/193)
=> Prepare test tender data for open** tests

op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/qualification.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/194)
=> Small fix for auction test and qualification keywords

op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/qualification.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/195)
=> Fix log lots ids in artifact

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/qualification.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/196)
=> Caching data for item and lot questions

op_robot_tests/tests_files/auction.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/cancelation.robot, op_robot_tests/tests_files/contract.robot, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/qualification.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/197)
=> Update post-base tests

op_robot_tests/tests_files/aboveThreshold.robot, op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/openProcedure.robot, op_robot_tests/tests_files/service_keywords.py, op_robot_tests/tests_files/singleItemTenderComplaints.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/200)
=> Add number of items

op_robot_tests/tests_files/aboveThreshold.robot, op_robot_tests/tests_files/auction.robot, op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/openProcedure.robot, op_robot_tests/tests_files/service_keywords.py, op_robot_tests/tests_files/singleItemTenderComplaints.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/203)
=> Auction end date fix

op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/keywords.robot
Because we need this data in award complaints
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/204)
=> Add remembering of provider access token

op_robot_tests/tests_files/aboveThreshold.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/limited_keywords.robot, op_robot_tests/tests_files/singleItemTender.robot
Also added ${tender_uaid} into `Отримати інформацію із тендера` instead
of global variable being used.
It is a lot of addition ${tender_uaid} into keywords arguments, because
`Отримати інформацію з тендера` is very "popular".
Closes #182.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/178)
=> Add waiting for tender status switching

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/data/faker_data.json, op_robot_tests/tests_files/op_faker.py, op_robot_tests/tests_files/openProcedure.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/205)
=> Add aboveThreshold in openProcedure and fix faker

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/openProcedure.robot, op_robot_tests/tests_files/service_keywords.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/208)
=> Fix set_to_object

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/openProcedure.robot, op_robot_tests/tests_files/service_keywords.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/209)
=> Features of tender, lot and item

op_robot_tests/tests_files/auction.robot, op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/cancelation.robot, op_robot_tests/tests_files/contract.robot, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/openProcedure.robot, op_robot_tests/tests_files/qualification.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/213)
=> Update openProcedure after rebase

op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/limited_keywords.robot, op_robot_tests/tests_files/negotiation.quick.robot, op_robot_tests/tests_files/negotiation.robot, op_robot_tests/tests_files/reporting.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/215)
=> Add initial data params for limited procurement

op_robot_tests/tests_files/auction.robot, op_robot_tests/tests_files/contract.robot, op_robot_tests/tests_files/qualification.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/220)
=> Tags unification

op_robot_tests/tests_files/openProcedure.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/221)
=> Fix delete meat tests tag

buildout.cfg, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/223)
=> UUB broker addition

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/227)
=> Add aps (brokers, users)

buildout.cfg, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/230)
=> APStender broker addition

op_robot_tests/tests_files/arguments_files/argfile_below_minimal.txt, op_robot_tests/tests_files/arguments_files/argfile_openeu_minimal.txt, op_robot_tests/tests_files/arguments_files/argfile_openua_minimal.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/231)
=> Add minimal argument files

op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/keywords.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/232)
=> Move `Отримати дані із скарги...` to op_client.robot

buildout.cfg, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/234)
=> ZTV broker addition

op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/217)
=> Fix error with tender indexation

op_robot_tests/tests_files/initial_data.py
Set right value to items.unit.name and items.unit.name_ru with unit.code = KGM.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/224)
=> Kilogram fix

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/openProcedure.robot, op_robot_tests/tests_files/service_keywords.py, robot_tests_arguments/competitive_dialogue.txt
add test_tender_data_competitive_dialogue
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/237)
=> Devel add competitive dialogue 2

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/244)
=> Update ztv data in brokers/users.yaml

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/246)
=> Update uub data in brokers.yaml

op_robot_tests/tests_files/initial_data.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/247)
=> add availableLanguage only if procurementMethodType not competitiveDialogueEU

op_robot_tests/tests_files/initial_data.py
Remove additionalClassifications data from initial_data
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/250)
=> new initial data without additionalClassifications

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/249)
=> add new brokers for eauction

op_robot_tests/tests_files/singleItemAuction.robot
Remove additionalClassifications tests from singleItemAuction.robot
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/252)
=> singleItemAuction.robot without additionalClassifications tests

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/254)
=> Update aps data in brokers/users.yaml

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/258)
=> change homepage and brokers sync time

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/260)
=> add DZOauctions users and edit DZO user in brokers.yaml and users.yaml

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/262)
=> Update etender data in brokers/users.yaml

op_robot_tests/tests_files/brokers/openprocurement_client.robot
Пропонується виправлення для "Отримати посилання на аукціон для глядача" та "Отримати посилання на аукціон для учасника"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/261)
=> Fix field name and condition for auction link getter

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/265)
=> Fix version of openprocurement-client egg in buildout.cfg

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/266)
=> Update ubiz data in brokers/users.yaml

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/267)
=> Update etender data (timeout) in brokers/users.yaml

op_robot_tests/tests_files/data/brokers.yaml
Increase enquiry period to make tests for viewer role work on .OP Test Stand (machines Jenkins)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/269)
=> Update etender data in brokers/users.yaml (enquiry period)

op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/brokers/openprocurement_client_helper.py, op_robot_tests/tests_files/cancelation.robot, op_robot_tests/tests_files/keywords.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/270)
=> Update work with documents in cancelation.robot

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
Add brizol broker to users.yaml and brokers.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/271)
=> Brizol Broker

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/274)
=> Switch SmartTender driver to eauction branch

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/276)
=> Update etender data in brokers/users.yaml (timeout_on_wait)

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/277)
=> Switch Ubiz driver to eauction branch

op_robot_tests/tests_files/aboveThreshold_keywords.robot, op_robot_tests/tests_files/auction.robot, op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/cancelation.robot, op_robot_tests/tests_files/complaints.robot, op_robot_tests/tests_files/contract_signing.robot, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/negotiation.quick.robot, op_robot_tests/tests_files/negotiation.robot, op_robot_tests/tests_files/openProcedure.robot, op_robot_tests/tests_files/qualification.robot, op_robot_tests/tests_files/reporting.robot, robot_tests_arguments/below.txt, robot_tests_arguments/below_simple.txt, robot_tests_arguments/competitive_dialogue.txt, robot_tests_arguments/competitive_dialogue_simple.txt, robot_tests_arguments/openeu.txt, robot_tests_arguments/openeu_simple.txt, robot_tests_arguments/openua.txt, robot_tests_arguments/openua_simple.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/278)
=> Make global/suite variables uppercase

op_robot_tests/tests_files/aboveThreshold_keywords.robot, op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot
Add tender_uaid to keywords arguments because it was missed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/280)
=> Add tender_uaid to arguments

op_robot_tests/tests_files/singleItemAuction.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/284)
=> Add tags in order to exclude testcases for DZO viewer

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/273)
=> Update  publicportal data in brokers/users.yaml

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/keywords.robot
To make code more readable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/286)
=> Note `Create Dictionary` with two and more arguments in a few rows

op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/resource.robot
FIrst patch is here #278.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/288)
=> Make global/suite variables uppercase (second patch)

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/289)
=> Add brizol repo to buildout.cfg

op_robot_tests/tests_files/resource.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/290)
=> Update api_version to dev

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/291)
=> Add polonex repo into buildout.cfg

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/cancelation.robot, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/service_keywords.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/296)
=> Cancellations update

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/298)
=> Change test data for PrivatMarket

buildout.cfg, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/300)
=> Change properties for publicbid (eAuction)

buildout.cfg, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/297)
=> Add upetem broker to users. and brokers.yaml

op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/301)
=> Change urls for testing

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/302)
=> Create Brizolauction data in brokers/users.yaml

buildout.cfg, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/295)
=> Add Alfa portal data

op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/304)
=> Update users.yaml for alfa

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/305)
=> Change tender period and urls

buildout.cfg
Change work branch for PrivatMarket (branch=eauction)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/306)
=> Change work branch for PrivatMarket

op_robot_tests/tests_files/data/users.yaml
uatenders users.yaml для аукціону
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/309)
=> uatenders users.yaml для аукціону

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/310)
=> Create opentenderauction and uaceauction data in brokers/users.yaml

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/311)
=> Add opentender and uace repo into buildout.cfg

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
changes for times latancies
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/312)
=> changes for times latancy

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/313)
=> Update etender data

op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/keywords.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/315)
=> Виправив коментарі до #299

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/314)
=> Update etender data in brokers.yaml (timeout_on_wait)

op_robot_tests/tests_files/aboveThreshold_keywords.robot, op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/318)
=> Remove return statements where were redundant

op_robot_tests/tests_files/service_keywords.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/320)
=> Finally remove outdated code!!!

op_robot_tests/tests_files/auction.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/keywords.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/324)
=> Changes for auction

op_robot_tests/tests_files/auction.robot, robot_tests_arguments/dgf_financial.txt, robot_tests_arguments/dgf_financial_simple.txt, robot_tests_arguments/dgf_other.txt, robot_tests_arguments/dgf_other_simple.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/325)
=> Edit tags, fix waiting time for auction end

robot_tests_arguments/dgf_financial.txt, robot_tests_arguments/dgf_financial_simple.txt, robot_tests_arguments/dgf_other.txt, robot_tests_arguments/dgf_other_simple.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/327)
=> Remove tags from argument files

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/openProcedure.robot, robot_tests_arguments/dgf_financial.txt, robot_tests_arguments/dgf_other.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/331)
=> Add financial license and edit tags

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/openProcedure.robot, robot_tests_arguments/dgf_financial.txt, robot_tests_arguments/dgf_other.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/332)
=> Edit tags, delete unnecessary keywords

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/contract_signing.robot, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/op_faker/op_faker_data.json, op_robot_tests/tests_files/openProcedure.robot, op_robot_tests/tests_files/qualification.robot, robot_tests_arguments/dgf_financial.txt, robot_tests_arguments/dgf_financial_simple.txt, robot_tests_arguments/dgf_other.txt, robot_tests_arguments/dgf_other_simple.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/334)
=> Modify qualifications and contracting

op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/338)
=> Update etender data in users.yaml

op_robot_tests/tests_files/auction.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/contract_signing.robot, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/openProcedure.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/340)
=> Bug fixes, edit tags, etc

op_robot_tests/tests_files/keywords.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/342)
=> Convert To Number - повертає float, а потрібно integer

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/339)
=> Create DZOauctions data in brokers/users.yaml

op_robot_tests/tests_files/data/users.yaml
Change urls for eauction
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/344)
=> Urls for eAuction

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
Change privatmarket test data
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/346)
=> Change privatmarket test data

op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/347)
=> Update DZOauctions data in brokers/users.yaml

op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/349)
=> Modify users for newtend

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/348)
=> Update opentenderauction and uaceauction data in brokers/users.yaml

op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/op_faker/op_faker.py, op_robot_tests/tests_files/op_faker/op_faker_data.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/350)
=> Fix minimal step and items generation

op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/op_faker/op_faker.py, op_robot_tests/tests_files/openProcedure.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/352)
=> Add support for dgfID

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
Налаштування для майданчика, чомусь вони не перенеслись в гілку 2.4.x
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/354)
=> polonex_up_setings

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/openProcedure.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/357)
=> Add changes to keywords and test cases to make them adapted for platforms

op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/358)
=> Change urls for eAuction

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/359)
=> Update Promauctions user data for eauction 2.4.x

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/361)
=> update ubiz data

op_robot_tests/tests_files/contract_signing.robot, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/openProcedure.robot, op_robot_tests/tests_files/qualification.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/363)
=> Add some changes

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/366)
=> Eauction master

op_robot_tests/tests_files/cancellation.robot, op_robot_tests/tests_files/keywords.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/367)
=> Changes for checking cancelled status

op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/370)
=> add provider uatenders

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/372)
=> Update DZOauctions in brokers.yaml

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/373)
=> add auction time

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/openProcedure.robot, op_robot_tests/tests_files/service_keywords.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/374)
=> Add fixed cancellation reasons

op_robot_tests/tests_files/openProcedure.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/375)
=> Remove dictionaries in minimalStep/value.amount modify test cases

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/376)
=> Update uace and opentender data in brokers.yaml

op_robot_tests/tests_files/contract_signing.robot, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/openProcedure.robot, op_robot_tests/tests_files/qualification.robot
Add keyword which combines LMD and synchronise to Teardown section where it is necessary
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/378)
=> Combine LMD and synchronisation into one keyword

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/379)
=> Update data for DZOauctions in brokers.yaml

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/381)
=> Update etender data in brokers.yaml

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/383)
=> Change tender period

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/384)
=> Ubiz: изменено время ождания 

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/386)
=> change browser on FF

op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/388)
=> revert again on chrome

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/op_faker/op_faker_data.json, op_robot_tests/tests_files/openProcedure.robot, op_robot_tests/tests_files/service_keywords.py, robot_tests_arguments/dgf_financial.txt, robot_tests_arguments/dgf_financial_simple.txt, robot_tests_arguments/dgf_other.txt, robot_tests_arguments/dgf_other_simple.txt
Also, checking items belonging to different CAV groups, add tag for test case checking procurement method type, add test cases checking an ability to modify forbidden fields.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/389)
=> Create lots with items from different CAV group

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/openProcedure.robot, op_robot_tests/tests_files/service_keywords.py, robot_tests_arguments/dgf_financial.txt, robot_tests_arguments/dgf_other.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/390)
=> Loading new documents to lot

op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/op_faker/op_faker.py, op_robot_tests/tests_files/openProcedure.robot, op_robot_tests/tests_files/service_keywords.py, robot_tests_arguments/dgf_financial.txt, robot_tests_arguments/dgf_other.txt
Add dgfDecisionDate, dgfDecisionID and tenderAttempts fields
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/391)
=> Add new fields

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/openProcedure.robot, robot_tests_arguments/dgf_financial.txt, robot_tests_arguments/dgf_other.txt
New offline document type
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/392)
=> Add loading of x_dgfAssetFamiliarization document

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/394)
=> up_polonex

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/openProcedure.robot, robot_tests_arguments/dgf_financial.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/393)
=> Check the inability to add and remove items

op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/openProcedure.robot, op_robot_tests/tests_files/service_keywords.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/397)
=> Modify tenderAttempts

op_robot_tests/tests_files/resource.robot, op_robot_tests/tests_files/service_keywords.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/398)
=> Modify compare_tender_attempts

op_robot_tests/tests_files/aboveThreshold_keywords.robot, op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/brokers/openprocurement_client_helper.py
Fixes #319.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/401)
=> Get bid before search document by doc_id

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/364)
=> APS Market: Change brokers.yaml and users.yaml

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/400)
=> fixed auction time

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/402)
=> UBIZ: add intrevals

buildout.cfg, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/406)
=> Update ueex data in buildout.cfg/brokers/users.yaml

op_robot_tests/tests_files/aboveThreshold_keywords.robot, op_robot_tests/tests_files/auction.robot, op_robot_tests/tests_files/contract_signing.robot, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/negotiation.quick.robot, op_robot_tests/tests_files/negotiation.robot, op_robot_tests/tests_files/service_keywords.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/408)
=> Add keyword with typing in console during waiting for some date

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/410)
=> Update etenter data in broker.yaml

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/415)
=> update enquiry period

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/416)
=> edit config

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/417)
=> edit time auction

buildout.cfg, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/418)
=> level II and level IV

buildout.cfg, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
Adding ecommodity
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/420)
=> Adding ecommodity

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/423)
=> Update brizol data in brokers.yaml and users.yaml

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/422)
=> налаштування для etc та e-trading

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/425)
=> Update govfound data in brokers.yaml and users.yaml

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/429)
=> Update aukzionua data in brokers.yaml and users.yaml

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/428)
=> Update katerynoslav data in brokers/users.yaml

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/430)
=> new brokers

op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/433)
=> Update centrex data in users.yaml

op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/434)
=> Changes for PrivatMarket users

buildout.cfg, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/436)
=> Update kif data in buildout/brokers/users.yaml

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/438)
=> Add brokers data in brokers/users.yaml

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/440)
=> Update uisce data in brokers/users.yaml

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/443)
=> Update zupb data in brokers/users.yaml

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/444)
=> Update epsilon data in brokers/users.yaml

op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/445)
=> Change user's names in users.yaml

op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/450)
=> etrade: Level II and Level IV

op_robot_tests/tests_files/awarding.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, robot_tests_arguments/dgf_financial_active_disqualification.txt, robot_tests_arguments/dgf_financial_verification_disqualification.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/461)
=> Change awarding

op_robot_tests/tests_files/awarding.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/462)
=> Change award index

op_robot_tests/tests_files/awarding.robot, op_robot_tests/tests_files/initial_data.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/463)
=> Change bid_value

op_robot_tests/tests_files/awarding.robot, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/openProcedure.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/465)
=> Verifying minimalStep for all users

op_robot_tests/tests_files/awarding.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/471)
=> Remove data from cache

op_robot_tests/tests_files/service_keywords.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/470)
=> Prefer lesser numbers for the 'accelerator' value

op_robot_tests/tests_files/data/brokers.yaml
Changed value for accelerator for broker SmartTender
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/473)
=> SmartTender: accelerator value

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/469)
=> Update Privatmarket test data

.gitignore, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/472)
=> Eauction awarding 2.1

op_robot_tests/tests_files/data/brokers.yaml
accelerator ecommodity = 360
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/476)
=> Зміни для awarding 2.1

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/478)
=> Update publicbid data in brokers/users.yaml

op_robot_tests/tests_files/data/brokers.yaml
update uatenders date (provider1:      uatenders_Provider1) in brokers.yaml file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/477)
=> Update uatenders data in brokers.yaml

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/480)
=> UBIZ: change accelerator

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/482)
=> Change accelerator in brokers.yaml for ueex/kif/tbkmfb/katerynoslav

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/486)
=> update broker and user

buildout.cfg, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/484)
=> Update alltenders data in brokers/users.yaml

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/488)
=> Update DZO data in brokers/users.yaml

op_robot_tests/tests_files/data/users.yaml
change browser name "PhantomJS"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/491)
=> uatenders update users.yaml

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/492)
=> update accelerator time

op_robot_tests/tests_files/data/users.yaml
browsers changed on fireFox
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/493)
=> Browsers changed

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/496)
=> update accelerators on uatenders

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/497)
=> Update etender data in users.yaml, brokers.yaml

op_robot_tests/tests_files/complaints.robot, op_robot_tests/tests_files/negotiation.robot, op_robot_tests/tests_files/openProcedure.robot, robot_tests_arguments/openeu_testing.txt, robot_tests_arguments/openua_testing.txt, robot_tests_arguments/single_item_tender.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/467)
=> Changes for testing marketplaces

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml, op_robot_tests/tests_files/keywords.robot
Update alltenders data in brokers/users.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/495)
=> Alltenders

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/complaints.robot, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/openProcedure.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/499)
=> Update Complaints test suite

op_robot_tests/tests_files/negotiation.quick.robot, op_robot_tests/tests_files/negotiation.robot, op_robot_tests/tests_files/op_faker/op_faker.py, op_robot_tests/tests_files/op_faker/op_faker_data.json, op_robot_tests/tests_files/openProcedure.robot, op_robot_tests/tests_files/reporting.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/501)
=> Adjust items classification schemes to current requirements

buildout.cfg, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
Signed-off-by: Sergey Titarchuk <s.titarchuk@a-express.com.ua>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/504)
=> Update alltenders brokers/users.yaml, buildout.cfg.

robot_tests_arguments/openeu_testing.txt, robot_tests_arguments/openua_testing.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/506)
=> Delete tags causing fails

buildout.cfg, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/507)
=> Update data users/brokers.yaml and buildout.cfg for broker.kapitalist

op_robot_tests/tests_files/negotiation.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/508)
=> Add complaintPeriod.endDate view test case

op_robot_tests/tests_files/complaints.robot, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/509)
=> Add lot title view test case

op_robot_tests/tests_files/complaints.robot, op_robot_tests/tests_files/openProcedure.robot, robot_tests_arguments/single_item_tender.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/512)
=> Minor changes to test files

op_robot_tests/tests_files/service_keywords.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/513)
=> Prefer lesser numbers for the accelerator value

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/519)
=> changed data for PMarket in broker and users .yaml

buildout.cfg, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/520)
=> Update 25h8 broker/users.yaml

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/openProcedure.robot, op_robot_tests/tests_files/qualification.robot, robot_tests_arguments/competitive_dialogue.txt, robot_tests_arguments/competitive_dialogue_simple.txt, robot_tests_arguments/openeu.txt, robot_tests_arguments/openeu_simple.txt, robot_tests_arguments/openua.txt, robot_tests_arguments/openua_simple.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/511)
=> Додав тест для перевірки роботи bot_identification

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/data/brokers.yaml
Залежить від https://github.com/openprocurement/openprocurement.client.python/pull/63
В коді були некоректні вказані назви для змінних.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/524)
=> Fix check for award

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/brokers/openprocurement_client_helper.py, op_robot_tests/tests_files/contract_signing.robot, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/service_keywords.py, robot_tests_arguments/below.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/457)
=> Update Contract_signing test suite

op_robot_tests/tests_files/auction.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/530)
=> Add auction.robot

buildout.cfg, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/brokers/openprocurement_client_helper.py, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/resource.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/528)
=> Add Document Service support into eauction-2.4.x

buildout.cfg, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/brokers/openprocurement_client_helper.py, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/resource.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/529)
=> Add Document Service support into eauction-devel

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/535)
=> Update epsilon data in users.yaml, brokers.yaml

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/542)
=> Update epsilon data in brokers.yaml

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/540)
=> added new broker 'palata'

buildout.cfg, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/543)
=> Update tirex data in users.yaml, brokers.yaml

buildout.cfg, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/547)
=> Change buildout, broker and user info for uub

op_robot_tests/tests_files/auction.robot, op_robot_tests/tests_files/op_faker/op_faker_data.json
Прибрали 4 об'єкта з списку об'єктів procuringEntities, для яких повертається 404 не знайдено.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/539)
=> Fix procuring entities list

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/537)
=> Adding configuration for tovprof

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/549)
=> Update ukin data in brokers/users.yaml

buildout.cfg, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/550)
=> Change data for agrex

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/551)
=> palata: change intervals

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/555)
=> Change tbetb broker name to prozora

buildout.cfg, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/559)
=> Add broker vertas buildout/users/brokers

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/560)
=> Add data for podilska users/brokers

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/openProcedure.robot, op_robot_tests/tests_files/service_keywords.py, robot_tests_arguments/competitive_dialogue.txt, robot_tests_arguments/competitive_dialogue_UA.txt, robot_tests_arguments/competitive_dialogue_simple.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/561)
=> Update Competitive Dialogue procedure

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/565)
=> update uisec, ukin and zupb data in brokers\users.yaml

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/566)
=> added provider1 in users and brokers .yaml

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/567)
=> eligbl crit const delete

robot_tests_arguments/competitive_dialogue.txt, robot_tests_arguments/competitive_dialogue_UA.txt, robot_tests_arguments/competitive_dialogue_simple.txt, robot_tests_arguments/openeu.txt, robot_tests_arguments/openeu_simple.txt, robot_tests_arguments/openua.txt, robot_tests_arguments/openua_simple.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/568)
=> Temporary remove edrpou tags

op_robot_tests/tests_files/data/users.yaml
changed browser to firefox
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/569)
=> changed browser to firefox

op_robot_tests/tests_files/data/brokers.yaml
accelerator changed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/571)
=> accelerator changed

op_robot_tests/tests_files/keywords.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/570)
=> update 'Дочекатись синхронізації з майданчиком'

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/brokers/openprocurement_client_helper.py, op_robot_tests/tests_files/contract_management.robot, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/op_faker/op_faker.py, op_robot_tests/tests_files/op_faker/op_faker_data.json, op_robot_tests/tests_files/qualification.robot, op_robot_tests/tests_files/service_keywords.py, robot_tests_arguments/below.txt, robot_tests_arguments/openeu.txt, robot_tests_arguments/openua.txt
This is an extended and improved version of pull request #239 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/536)
=> Contract management procedure

op_robot_tests/tests_files/contract_signing.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/572)
=> Add the contract`s last index

op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/op_faker/op_faker_data.json, op_robot_tests/tests_files/openProcedure.robot, op_robot_tests/tests_files/service_keywords.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/575)
=> flexfields

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/openProcedure.robot, op_robot_tests/tests_files/service_keywords.py
Команди запуску:
bin/op_tests -s openprocedure -A robot_tests_arguments/файл_аргумент -i get_file_properties
bin/op_tests -s openprocedure -i compare_file_properties
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/577)
=> compare file properties

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/579)
=> add changes from 2.3.x_new

op_robot_tests/tests_files/initial_data.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/582)
=> Remove deliveryDate field

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/589)
=> aladdin broker and users

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/591)
=> Alltenders update brokers.yaml/users.yaml

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/592)
=> update brokers data for belowThreshold

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/595)
=> update urls and periods

op_robot_tests/tests_files/openProcedure.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/596)
=> update 'Відображення заголовку нецінового показника на тендер'

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/service_keywords.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/598)
=> Remove features from generate_bid_data

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/600)
=> accelerator tender_lot_claim

op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/service_keywords.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/603)
=> Change generation bid data for dgfInsider

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/604)
=> +15m for EU and UA

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/605)
=> belowThreshold period for award complaint

op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/606)
=> change baseUrl in users.yaml

op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/610)
=> Change vidrodzhennia base url

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/611)
=> restore Below period

op_robot_tests/tests_files/data/users.yaml
update browser -> chrome uatenders
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/608)
=> update browser -> chrome uatenders

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/612)
=> credentials changes for uisce

op_robot_tests/tests_files/data/users.yaml
changed credentials for users access to new testing server
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/615)
=> Brokers credentials changed

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/613)
=> Update brokers & users yaml for neb

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/616)
=> Update brokers and users yaml for brizol

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/618)
=> Update brokers and users yaml for tbepsilon

op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/619)
=> Update usersyaml for centrex

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/620)
=> Set belowThreshold intervals for aladdin

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/622)
=>  period for OpenEU

op_robot_tests/tests_files/awarding.robot, op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/data/users.yaml, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/insider_full.robot, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/service_keywords.py, robot_tests_arguments/dgf_insider_dutch_auction.txt, robot_tests_arguments/dgf_insider_full_auction.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/624)
=> Tests for dutch auction

op_robot_tests/tests_files/insider_full.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/627)
=> Add view_tenderPeriod_endDate test case

op_robot_tests/tests_files/insider_full.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/628)
=> Fix tenderPeriod_view test case

op_robot_tests/tests_files/insider_full.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/629)
=> Edit auction pause message

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/630)
=> change accelerator for insider

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/631)
=> update accelerator for dgfInsider_uatenders

op_robot_tests/tests_files/data/users.yaml, op_robot_tests/tests_files/insider_full.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/632)
=> Change window size and timeout

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/633)
=> change accelerator

op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/634)
=> browser_change for polonex, etc, etrading

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/636)
=> change browser and timeout

op_robot_tests/tests_files/data/brokers.yaml
Прошу прийняти зміни в Brokers.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/638)
=> Update smarttender data in brokers.yaml

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/639)
=> update users.yaml and brokers.yaml for PrivatMarket

op_robot_tests/tests_files/data/users.yaml
зміна браузера на chrome
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/626)
=> ecommodity users.yaml

op_robot_tests/tests_files/insider_full.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/640)
=> Change timeout

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/644)
=> Update brokers yaml for brizol

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/645)
=> changed browser uisce

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/641)
=> pzo v.2 update

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/647)
=> Update brokers yaml for DTO

op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/646)
=> Changed browser data on Etender

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/648)
=>  update accelerator for dgfInsider

op_robot_tests/tests_files/data/users.yaml
provider new login name
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/649)
=> provider new login name

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/652)
=> Change timings and users

op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/653)
=> Fix yaml error

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/654)
=> Change data in E-tender brokers.yaml

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/658)
=> Change timings

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/659)
=> Change timeout_on_wait to 120 seconds

op_robot_tests/tests_files/awarding.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/660)
=> Add wait_for_verificationEndDate test case

op_robot_tests/tests_files/op_faker/op_faker_data.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/665)
=> Change CAV to CAV-PS

op_robot_tests/tests_files/openProcedure.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/666)
=> add test case "Відображення гарантійного внеску"

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/667)
=> ecommodity CBD2

op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/668)
=> Change users params for uub place

op_robot_tests/tests_files/data/users.yaml
Brokers credentials fix for CDB_2 project
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/671)
=> Brokers credentials fix for CDB_2 project

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/669)
=> Update upetem data in brokers/users.yaml

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/672)
=> Update tbums, kme, sets and biddingtime data in brokers/users.yaml

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/674)
=> ubiz:brokers

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/679)
=> Set params for tenderonline and tsbgalcontract

op_robot_tests/tests_files/keywords.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/681)
=> Update "Дочекатись дати початку періоду кваліфікації"

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/682)
=> update brokers and user for cbd2

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
tender owner changed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/673)
=> owner changed

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/678)
=> Add new brokers

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/683)
=> ubiz:brokers fix time

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/684)
=> Update users yaml for DTO

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/675)
=> Update etender data in users.yaml and brokers.yaml

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
Прошу прийняти зміни для проходження автотестів.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/680)
=> Update smarttender data in brokers/users.yaml

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/686)
=> Update users and brokers yaml for UACE broker

op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/690)
=> commit for cdb2

buildout.cfg, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/691)
=> Add 25h8 to users and brokers yaml

op_robot_tests/tests_files/data/users.yaml
update uatenders data in users.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/688)
=> update uatenders data in users.yaml

op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/693)
=> Update users yaml for UACE

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/694)
=> Update brokers yaml for aukzionua

op_robot_tests/tests_files/data/brokers.yaml
Signed-off-by: Sergey Titarchuk <s.titarchuk@a-express.com.ua>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/695)
=> Change brokers.yaml from alltenders

op_robot_tests/tests_files/resource.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/697)
=> change api_version

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/685)
=> Add brokers and users yaml for KPMG broker

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/negotiation.quick.robot, op_robot_tests/tests_files/negotiation.robot, op_robot_tests/tests_files/op_faker/op_faker.py, op_robot_tests/tests_files/op_faker/op_faker_data.json, op_robot_tests/tests_files/openProcedure.robot, op_robot_tests/tests_files/reporting.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/696)
=> Add tests for integration with MOZ

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/698)
=> added kme, sets, biddingtime to brokers\users.yaml

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/700)
=> Update pag and ctb data in brokers/users.yaml

op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/703)
=> changed start page for users at zupb, kme, sets and biddingtime

op_robot_tests/tests_files/cancellation.robot, op_robot_tests/tests_files/complaints.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/705)
=> Add MOZ_INTEGRATION parameter to complaints and cancellation suites

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/706)
=> Update users and brokers yaml for 25h8

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/707)
=> Add 25h8 to buildout cfg

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/708)
=> add new broker

robot_tests_arguments/dgf_cancel_bid_bestbid.txt, robot_tests_arguments/dgf_cancel_bid_sealedbid.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/709)
=> remove tender_view_unit_code

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/710)
=> Optimized timeouts and accelerations, changed browser window size

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/711)
=> Update acceleration for uub/akc/tsbgalcontract

op_robot_tests/tests_files/auction.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/712)
=> Fix display of an auction start date

op_robot_tests/tests_files/keywords.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/713)
=> update "Отримати останній індекс"

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/715)
=> update accelerator pag/ctb

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/717)
=> Update acceleration for 25h8 broker

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/720)
=> Update acceleration for KPMG broker

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/723)
=> decrease insider auction acceleration

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
Signed-off-by: Sergey Titarchuk <s.titarchuk@a-express.com.ua>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/724)
=> Alltenders update brokers and users

op_robot_tests/tests_files/openProcedure.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/727)
=> add critical and non-critical tags

op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/negotiation.robot, op_robot_tests/tests_files/op_faker/op_faker_data.json, op_robot_tests/tests_files/openProcedure.robot, robot_tests_arguments/below.txt, robot_tests_arguments/below_funders.txt, robot_tests_arguments/below_simple.txt, robot_tests_arguments/competitive_dialogue.txt, robot_tests_arguments/competitive_dialogue_UA.txt, robot_tests_arguments/competitive_dialogue_simple.txt, robot_tests_arguments/openUAdefense_one_bid.txt, robot_tests_arguments/openeu.txt, robot_tests_arguments/openeu_simple.txt, robot_tests_arguments/openeu_testing.txt, robot_tests_arguments/openua.txt, robot_tests_arguments/openua_simple.txt, robot_tests_arguments/openua_testing.txt, robot_tests_arguments/single_item_tender.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/730)
=> Edit id classification and data for planning

buildout.cfg, op_robot_tests/tests_files/op_faker/op_faker_data.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/733)
=> Set broker name

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/734)
=> Add allbiz broker to users and brokers yaml

op_robot_tests/tests_files/negotiation.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/735)
=> edit tag for 'Можливість укласти угоду для переговорної процедури'

op_robot_tests/tests_files/resource.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/736)
=> Change Document Service host url

op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/739)
=> Change browser to Firefox for allbiz

op_robot_tests/tests_files/op_faker/op_faker_data.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/741)
=> edit telephone for contactPoint

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/743)
=> UBIZ: update broker

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/746)
=> change duration of period

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/740)
=> 1-4 level tests

op_robot_tests/tests_files/op_faker/op_faker_data.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/749)
=> edit telephone in contactPoint

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/op_faker/op_faker.py, op_robot_tests/tests_files/op_faker/op_faker_data.json, op_robot_tests/tests_files/openProcedure.robot, op_robot_tests/tests_files/service_keywords.py, robot_tests_arguments/dgf_other_full.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/742)
=> Add tests for rectificationPeriod and item.address related fields

op_robot_tests/tests_files/openProcedure.robot, robot_tests_arguments/dgf_no_awards.txt, robot_tests_arguments/dgf_one_award_unsuccessful.txt, robot_tests_arguments/dgf_one_bid_successful.txt, robot_tests_arguments/dgf_one_bid_unsuccessful.txt, robot_tests_arguments/dgf_other_active_disqualification.txt, robot_tests_arguments/dgf_other_bid_cancellation.txt, robot_tests_arguments/dgf_other_full.txt, robot_tests_arguments/dgf_other_payment_disqualification.txt, robot_tests_arguments/dgf_other_verification_disqualification.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/750)
=> Add new tag to scenarios

op_robot_tests/tests_files/keywords.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/752)
=> update "Звірити координати доставки тендера"

robot_tests_arguments/competitive_dialogue.txt, robot_tests_arguments/openUAdefense_one_bid.txt, robot_tests_arguments/openeu.txt, robot_tests_arguments/openua.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/753)
=> remove resolve_tender_claim and resolve_lot_claim from argument files

op_robot_tests/tests_files/negotiation.robot, op_robot_tests/tests_files/openProcedure.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/751)
=> rename test cases

op_robot_tests/tests_files/initial_data.py, robot_tests_arguments/competitive_dialogue.txt, robot_tests_arguments/openUAdefense_one_bid.txt, robot_tests_arguments/openeu.txt, robot_tests_arguments/openua.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/755)
=> change generation deliveryDate and remove claim tags from argument files

op_robot_tests/tests_files/auction.robot, op_robot_tests/tests_files/awarding.robot, op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/contract_signing.robot, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/insider_full.robot, op_robot_tests/tests_files/openProcedure.robot, op_robot_tests/tests_files/service_keywords.py, robot_tests_arguments/dgf_cancel_bid_bestbid.txt, robot_tests_arguments/dgf_cancel_bid_sealedbid.txt, robot_tests_arguments/dgf_financial_active_disqualification.txt, robot_tests_arguments/dgf_financial_full.txt, robot_tests_arguments/dgf_financial_payment_cancellation.txt, robot_tests_arguments/dgf_financial_second_award_complete.txt, robot_tests_arguments/dgf_financial_simple.txt, robot_tests_arguments/dgf_financial_verification_cancellation.txt, robot_tests_arguments/dgf_financial_verification_disqualification.txt, robot_tests_arguments/dgf_insider_dutch_auction.txt, robot_tests_arguments/dgf_insider_full_auction.txt, robot_tests_arguments/dgf_other_active_disqualification.txt, robot_tests_arguments/dgf_other_full.txt, robot_tests_arguments/dgf_other_payment_cancellation.txt, robot_tests_arguments/dgf_other_simple.txt, robot_tests_arguments/dgf_other_verification_cancellation.txt, robot_tests_arguments/dgf_other_verification_disqualification.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/756)
=> Update awarding scenarios (awarding_3.0)

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/763)
=> Update livtrade data in brokers/users.yaml

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/openProcedure.robot, robot_tests_arguments/dgf_other_full.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/764)
=> Test uploading/editing documents during rectification period

op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/resource.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/767)
=> Add public endpoint

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/complaints.robot, robot_tests_arguments/below_after_resolved_award_complaint.txt, robot_tests_arguments/below_before_resolved_award_complaint.txt, robot_tests_arguments/openua_award_complaint.txt, robot_tests_arguments/openua_tender_lot_complaint.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/770)
=> Complaints openua 

op_robot_tests/tests_files/op_faker/op_faker.py, op_robot_tests/tests_files/openProcedure.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/758)
=> Remove additionalClassification for item with cpv id 99999999-9

robot_tests_arguments/below_before_resolved_award_complaint.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/771)
=> remove award_complaint from below_before_resolved_award_complaint.txt

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/776)
=> izi +brokers, +users  pull request #2

op_robot_tests/tests_files/complaints.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/777)
=> add provider2 to USED_ROLES

op_robot_tests/tests_files/planning.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/779)
=> remove test case "Відображення amountNet бюджету"

op_robot_tests/tests_files/complaints.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/780)
=> add Setup and Teardown to test case "Відображення задоволення вимоги"

robot_tests_arguments/single_item_tender.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/787)
=> add tag  qualification_add_doc_to_first_award  to single_item_tender.txt

op_robot_tests/tests_files/complaints.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/790)
=> add tags lot_complaint_draft and tender_complaint_draft

op_robot_tests/tests_files/complaints.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/791)
=> add tag award_complaint_draft

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/792)
=> Add getting items amount keyword

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/lot.robot, op_robot_tests/tests_files/service_keywords.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/793)
=> Edit Create Artefact and pass ASSET_UAID as parameter

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/keywords.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/795)
=> Add auction conditions and Reload Page keywords

op_robot_tests/tests_files/keywords.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/796)
=> Edit Create Artifact keyword

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
ssp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/797)
=> change login/browser

robot_tests_arguments/ssp_delete_lot.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/801)
=> Edit delete_lot scenario

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/802)
=> change timeout 150

op_robot_tests/tests_files/lot.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/803)
=> Add synchronization with broker

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/lot.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/804)
=> Add waiting for deleted lot status

op_robot_tests/tests_files/initial_data.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/806)
=> Change decisionDate format

buildout.cfg, op_robot_tests/tests_files/lot.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/807)
=> Change branch for biddingtime broker

op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/812)
=> Зміни у brokers/users.yaml для майданчика biddingtime

buildout.cfg, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/810)
=> Update users for platforms

op_robot_tests/tests_files/initial_data.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/814)
=> Add bankAccount details

op_robot_tests/tests_files/op_faker/op_faker_data.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/815)
=> Add additionalContactPoints details

buildout.cfg, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/813)
=> Update user info for dzo

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/818)
=> Change branch in buildout

op_robot_tests/tests_files/lot.robot, robot_tests_arguments/ssp_bid_cancellation.txt, robot_tests_arguments/ssp_full_procedure.txt, robot_tests_arguments/ssp_one_bidder.txt, robot_tests_arguments/ssp_procedure_cancellation.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/821)
=> Edit tags in scenarios

op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/op_faker/op_faker_data.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/824)
=> Edit classification for assets

robot_tests_arguments/ssp_full_procedure.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/825)
=> Remove modify_doc_to_bid_by_provider test case

op_robot_tests/tests_files/openProcedure.robot, robot_tests_arguments/ssp_bid_cancellation.txt, robot_tests_arguments/ssp_one_bidder.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/827)
=> Add test cases for value.amount and minimalStep.amount

op_robot_tests/tests_files/openProcedure.robot, robot_tests_arguments/ssp_bid_cancellation.txt, robot_tests_arguments/ssp_full_procedure.txt, robot_tests_arguments/ssp_one_bidder.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/828)
=> Add tags to scenarios

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/829)
=> Change branch for brokers in buildout.cfg

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/830)
=> Change branch for Prom broker

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/831)
=> new user and broker for mp

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/834)
=> Changes accelerator and timeout_on_wait params

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/833)
=> Add periods for aukzionua

robot_tests_arguments/ssp_full_registry.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/835)
=> Add test case for rectificationPeriod

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/836)
=> Add periods for brizol

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/837)
=> upd intervals

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/838)
=> Change branch for ubiz broker

op_robot_tests/tests_files/service_keywords.py, op_robot_tests/tests_files/unittests/set_to_object.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/823)
=> Rewrite set_to_object() and related utility functions

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/monitoring.robot, robot_tests_arguments/dasu_cancelled.txt, robot_tests_arguments/dasu_closed.txt, robot_tests_arguments/dasu_completed.txt, robot_tests_arguments/dasu_stopped.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/839)
=> Dasu (part 2)

op_robot_tests/tests_files/insider_full.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/840)
=> Exclude add_financial_license test case from scenarios

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/841)
=> Palata: upd accelerator, auction delay

op_robot_tests/tests_files/auction.robot, op_robot_tests/tests_files/awarding.robot, op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/contract_signing.robot, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/service_keywords.py, robot_tests_arguments/ssp_awards_disqualification.txt, robot_tests_arguments/ssp_awards_disqualification_and_cancellation.txt, robot_tests_arguments/ssp_contracts_cancellation.txt, robot_tests_arguments/ssp_first_contract_cancellation.txt, robot_tests_arguments/ssp_full_procedure.txt, robot_tests_arguments/ssp_one_bidder_admission_disqualification.txt, robot_tests_arguments/ssp_one_bidder_contract_cancellation.txt, robot_tests_arguments/ssp_one_bidder_no_admission_protocol.txt, robot_tests_arguments/ssp_one_bidder_pending_disqualification.txt, robot_tests_arguments/ssp_procedure_cancellation.txt, robot_tests_arguments/ssp_second_award_complete.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/843)
=> Add tests for awarding 3.1

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/842)
=> Update periods for uace

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/844)
=> Set eauction_ssp branch

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/847)
=> Update timeout_on_wait for uace

op_robot_tests/tests_files/awarding.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/846)
=> fix indentation in awarding.robot

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/848)
=> Update periods for dzo

op_robot_tests/tests_files/awarding.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/849)
=> Check award status with viewer role

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/850)
=> Update periods for aukzionua and brizol

op_robot_tests/tests_files/initial_data.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/851)
=> Remove milliseconds from create_fake_date

op_robot_tests/tests_files/awarding.robot, robot_tests_arguments/ssp_one_bidder.txt, robot_tests_arguments/ssp_one_bidder_contract_cancellation.txt, robot_tests_arguments/ssp_one_bidder_pending_disqualification.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/854)
=> Combine the loading of the document and award disqualification

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/856)
=> fixed accelerator

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/857)
=> change timeout ecommodity

op_robot_tests/tests_files/contract_signing.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/858)
=> update test case "Відображення відредагованої вартості угоди"

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
TABUA: configs and credentials changed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/860)
=> config changed

op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/863)
=> Зміни у brokers\users.yaml для майданчика sets

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/865)
=> change_lot_accelerator

op_robot_tests/tests_files/keywords.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/866)
=> Increase waiting time for active.tendering period

op_robot_tests/tests_files/keywords.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/869)
=> Increase waiting time for changing status

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/contract_management.robot, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/keywords.robot, robot_tests_arguments/below.txt, robot_tests_arguments/esco_contract.txt, robot_tests_arguments/openeu.txt, robot_tests_arguments/openua.txt
Run command:
bin/op_tests -s openprocedure -A robot_tests_arguments/esco_contract.txt -v submissionMethodDetails:"quick(mode:fast-forward)" -v {"default":{"intervals":{"esco":{"enquiry":[0,0],"tender":[0,16]}}}} -v accelerator:8784
bin/op_tests -s qualification -A robot_tests_arguments/esco_contract.txt
bin/op_tests -s contract_signing -A robot_tests_arguments/esco_contract.txt
bin/op_tests -s contract_management -A robot_tests_arguments/esco_contract.txt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/855)
=> Esco contact management

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/monitoring.robot, robot_tests_arguments/dasu_cancelled.txt, robot_tests_arguments/dasu_closed.txt, robot_tests_arguments/dasu_completed.txt, robot_tests_arguments/dasu_stopped.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/870)
=> remove test case "Можливість додати документацію до об’єкта моніторингу"

op_robot_tests/tests_files/awarding.robot, op_robot_tests/tests_files/contract_signing.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/873)
=> Edit Cancel Contract test case

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/871)
=> Update periods for centrex

op_robot_tests/tests_files/contract_management.robot, robot_tests_arguments/openua.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/872)
=> add tag modify_contract_period

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/876)
=> Update periods for opentender

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/877)
=> Зміни стосовно прискорення у brokers\users.yaml для майданчика sets

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/878)
=> Зміни у стосовно прискорення у brokers.yaml для майданчика uisce

buildout.cfg, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/875)
=> Update users, brokers, buildout for etender

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/879)
=> Зміна коефіцієнту прискорення для майданчика sets

op_robot_tests/tests_files/initial_data.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/880)
=> Change accountNumber

op_robot_tests/tests_files/negotiation.quick.robot, op_robot_tests/tests_files/negotiation.robot, op_robot_tests/tests_files/op_faker/op_faker_data.json, op_robot_tests/tests_files/openProcedure.robot, op_robot_tests/tests_files/reporting.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/882)
=> MOZ update

op_robot_tests/tests_files/brokers/openprocurement_client_helper.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/884)
=> update retry_if_request_failed (eauction_ssp)

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/contract_signing.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/886)
=> add keyword "Звірити відображення дати ${field} контракту"

op_robot_tests/tests_files/initial_data.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/887)
=> Change accountNumber filed value

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/888)
=> add lot accelerator

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/889)
=> Change branch for brokers

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/890)
=> Change branch for torgibirgaukraine

op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/892)
=> change dasu_api_key

op_robot_tests/tests_files/data/brokers.yaml
branch - eauction_ssp 
platform -uatenders
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/891)
=> added lot accelerator for uatenders

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/895)
=> Зміни у brokers/users.yaml для майданчика mytender

op_robot_tests/tests_files/asset.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/896)
=> Remove rectificationPeriod related test case for assets

op_robot_tests/tests_files/brokers/openprocurement_client_helper.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/885)
=> update retry_if_request_failed (eauction-awarding-2.1)

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/897)
=> Зміни у brokers/users.yaml для майданчика avi

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/899)
=> Зміни у brokers/users.yaml для майданчика expagency

op_robot_tests/tests_files/lot.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/901)
=> Change the name of the test case

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/902)
=> Зміни у brokers/users.yaml для майданчиків expagency та livtrade

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/903)
=> Зміна акселератора для майданчиків avi, expagency, livtrade, та mytender

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/905)
=> Change auction period for uace

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
Зміни у brokers/users.yaml для майданчиків biddingtime, sets, uisce, mytender, livtrade, expagency та aukzionist
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/908)
=> Зміни у brokers/users.yaml для майданчиків biddingtime, sets, uisce, mytender, livtrade, expagency та aukzionist

buildout.cfg, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/907)
=> Update data for govfound

op_robot_tests/tests_files/lot.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/911)
=> Add roles to the lot test suite

buildout.cfg, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/912)
=> skyline_config_init

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/913)
=> add new auctions-accelerators(SSP) for uatenders

op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/914)
=> add new Login for uatenders_Owner and Viewer

op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/910)
=> Change params for podilska place

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/917)
=> fixed broker time

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/919)
=> fixed time

op_robot_tests/tests_files/contract_signing.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/920)
=> Change the order of test cases

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/921)
=> Fixed auction time part 2

op_robot_tests/tests_files/keywords.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/918)
=> update keyword Дочекатись дати закінчення періоду уточнень

op_robot_tests/tests_files/awarding.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/922)
=> Change contract index

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/923)
=> fixed lot time

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/924)
=> fixed time part 3

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/925)
=> Fixed accelerator time

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/926)
=> fixed accelerator time part 2

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/brokers/openprocurement_client_helper.py, op_robot_tests/tests_files/contract_management.robot, op_robot_tests/tests_files/contract_signing.robot, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/service_keywords.py, robot_tests_arguments/ssp_approval_milestone_notMet.txt, robot_tests_arguments/ssp_contracting_full.txt, robot_tests_arguments/ssp_financing_milestone_notMet.txt, robot_tests_arguments/ssp_milestones_partiallyMet.txt, robot_tests_arguments/ssp_reporting_milestone_notMet.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/927)
=> Add scenarios for contracting

robot_tests_arguments/ssp_approval_milestone_notMet.txt, robot_tests_arguments/ssp_financing_milestone_notMet.txt, robot_tests_arguments/ssp_milestones_partiallyMet.txt, robot_tests_arguments/ssp_reporting_milestone_notMet.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/929)
=> Add tag to scenarios

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/931)
=> Update data for dto

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/930)
=> Update time for bid

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/932)
=> add robot_tests.broker.aukzionist

op_robot_tests/tests_files/op_faker/op_faker_data.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/933)
=> Change procuringEntity.region field value

op_robot_tests/tests_files/contract_management.robot, robot_tests_arguments/ssp_approval_milestone_notMet.txt, robot_tests_arguments/ssp_contracting_full.txt, robot_tests_arguments/ssp_financing_milestone_notMet.txt, robot_tests_arguments/ssp_milestones_partiallyMet.txt, robot_tests_arguments/ssp_reporting_milestone_notMet.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/934)
=> Remove viewer tags from scenarios

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/935)
=> add robot_tests.broker.mytender

op_robot_tests/tests_files/contract_management.robot, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/keywords.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/936)
=> Fix milestones_partiallyMet scenario

op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/openProcedure.robot, op_robot_tests/tests_files/service_keywords.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/938)
=> update keyword Дочекатись дати закінчення періоду відповідей на запитання

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/939)
=> add robot_tests.broker.livtrade

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/940)
=> vidol params

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/941)
=> Change branch for cuex broker

op_robot_tests/tests_files/contract_signing.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/945)
=> Edit datePaid_view test case

op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/lot.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/948)
=> Add array of relatedProcesses to lots

op_robot_tests/tests_files/auction.robot, op_robot_tests/tests_files/auction_full.robot, op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/resource.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/947)
=> Configuration for regular expressions

buildout.cfg, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/949)
=> Add data for Setam

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/951)
=> added new broker c1ux

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/952)
=> Add c1ux broker

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/953)
=> Add pfts broker

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/954)
=> Зміна brokers/users.yaml для майданчика pfts

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/openProcedure.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/955)
=> Add changes related to rectificationPeriod

op_robot_tests/tests_files/lot.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/956)
=> Delete minimalStep_view test case for sellout.insider procedure

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/957)
=> c1ux upd broker params

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/958)
=> Зміна параметрів акселерації для майданчика avi

op_robot_tests/tests_files/contract_signing.robot, op_robot_tests/tests_files/openProcedure.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/959)
=> Add Update LAST_MODIFICATION_DATE and Compare Dates keywords

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/960)
=> Change branch for newtend broker

op_robot_tests/tests_files/openProcedure.robot, robot_tests_arguments/dgf_financial.txt, robot_tests_arguments/dgf_financial_full.txt, robot_tests_arguments/dgf_other.txt, robot_tests_arguments/dgf_other_full.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/961)
=> Add auction_guarantee_view test case

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/963)
=> c1ux updated broker params

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/965)
=> Update newtend data in brokers.yaml

op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/967)
=> Update newtend data in users.yaml

robot_tests_arguments/dgf_financial.txt, robot_tests_arguments/dgf_financial_full.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/968)
=> Remove delete_item test case

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/969)
=> Change parameters for setam

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/970)
=> Update accelerator for Setam

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/openProcedure.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/971)
=> Set minimalStep value for all users

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/973)
=> Update ssp params for kif

op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/contract_signing.robot, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/openProcedure.robot, op_robot_tests/tests_files/qualification.robot, op_robot_tests/tests_files/service_keywords.py, robot_tests_arguments/below.txt, robot_tests_arguments/below_funders.txt, robot_tests_arguments/below_funders_full.txt, robot_tests_arguments/below_simple.txt, robot_tests_arguments/competitive_dialogue_UA.txt, robot_tests_arguments/competitive_dialogue_simple.txt, robot_tests_arguments/framework_agreement.txt, robot_tests_arguments/openUAdefense_one_bid.txt, robot_tests_arguments/openeu.txt, robot_tests_arguments/openeu_simple.txt, robot_tests_arguments/openeu_testing.txt, robot_tests_arguments/openua.txt, robot_tests_arguments/openua_simple.txt, robot_tests_arguments/openua_testing.txt, robot_tests_arguments/single_item_tender.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/966)
=> СloseFrameworkAgreementUA (part 1)

buildout.cfg, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/brokers/openprocurement_client_helper.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/975)
=> change branch for openprocurement_client

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/976)
=> Fixed waiting time

op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/monitoring.robot, robot_tests_arguments/dasu_cancelled.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/977)
=> update keywords for dasu

op_robot_tests/tests_files/brokers/openprocurement_client.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/979)
=> update Подати цінову пропозицію

op_robot_tests/tests_files/keywords.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/980)
=> Change waiting time

op_robot_tests/tests_files/contract_management.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/981)
=> Change dateMet setting

buildout.cfg, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/982)
=> Add users setam

op_robot_tests/tests_files/monitoring.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/984)
=> update monitoring (cancellation)

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/985)
=> change accelerator for lots (setam)

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/986)
=> change accelerator for lots 100 (setam)

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/987)
=> change accelerator for lots 150 (setam)

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/988)
=> change accelerator for lots 50 (setam)

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/990)
=> change accelerator for lots 720 (setam)

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/contract_signing.robot, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/openProcedure.robot, op_robot_tests/tests_files/qualification.robot, op_robot_tests/tests_files/service_keywords.py, robot_tests_arguments/below.txt, robot_tests_arguments/below_funders.txt, robot_tests_arguments/below_funders_full.txt, robot_tests_arguments/below_simple.txt, robot_tests_arguments/competitive_dialogue.txt, robot_tests_arguments/competitive_dialogue_UA.txt, robot_tests_arguments/competitive_dialogue_simple.txt, robot_tests_arguments/esco_testing.txt, robot_tests_arguments/openUAdefense_one_bid.txt, robot_tests_arguments/openeu.txt, robot_tests_arguments/openeu_simple.txt, robot_tests_arguments/openeu_testing.txt, robot_tests_arguments/openua.txt, robot_tests_arguments/openua_simple.txt, robot_tests_arguments/openua_testing.txt, robot_tests_arguments/single_item_tender.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/991)
=> Esco testing

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/993)
=> Зміни у brokers\users.yaml для майданчика evropeyska

op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/monitoring.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/996)
=> update keyword Звірити статус об'єкта моніторингу

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/997)
=> Change periods for 25h8

op_robot_tests/tests_files/base_keywords.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/998)
=> udate keyword 'Можливість видалити  неціновий показник'

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/999)
=> Params for ecoex

op_robot_tests/tests_files/contract_signing.robot, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/initial_data.py, robot_tests_arguments/framework_agreement.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1002)
=> update for closeFrameworkAgreementUA

robot_tests_arguments/framework_agreement.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1006)
=> add tag tender_view_value to framework_agreement.txt

op_robot_tests/tests_files/brokers/openprocurement_client.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1009)
=> update "Завантажити документ в ставку"

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/contract_signing.robot, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/selection.robot, op_robot_tests/tests_files/service_keywords.py, robot_tests_arguments/below.txt, robot_tests_arguments/framework_selection.txt, robot_tests_arguments/openeu.txt, robot_tests_arguments/openeu_testing.txt, robot_tests_arguments/openua.txt, robot_tests_arguments/openua_testing.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1005)
=> closeFrameworkAgreementSelectionUA

robot_tests_arguments/esco_testing.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1011)
=> remove modify_bid_by_provider from esco_testing.txt

op_robot_tests/tests_files/op_faker/op_faker_data.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1012)
=> change data for funders

op_robot_tests/tests_files/aboveThreshold_keywords.robot, op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/openProcedure.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1010)
=> update for competitive dialogue

op_robot_tests/tests_files/initial_data.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1013)
=> change generation of  seconds for agreementDuration

op_robot_tests/tests_files/keywords.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1016)
=> update "Підготувати дані для створення предмету закупівлі"

op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/brokers/openprocurement_client_helper.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1017)
=> remove ds_client and add ds_config

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1020)
=> Updates for ecoex broker

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1021)
=> add ecoex broker

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1022)
=> add_accelerator

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1023)
=> Зміна параметру акселерації для майданчика avi

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1024)
=> Зміна параметрів акселерації для майданчика ukin

op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1025)
=> change browser settings for ukin

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1026)
=> UPD pag broker data

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1027)
=> change_accelerator_to_270

op_robot_tests/tests_files/base_keywords.robot, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/openProcedure.robot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1028)
=> Edit Add item test case

op_robot_tests/tests_files/initial_data.py, op_robot_tests/tests_files/lot.robot, op_robot_tests/tests_files/openProcedure.robot, robot_tests_arguments/ssp_full_registry.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1029)
=> Remove registrationFee field

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1032)
=> Add playtender broker to buildout

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1033)
=> Добавление параметров брокера fidda в brokers\users.yaml

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1036)
=> Добавление параметров брокера playtender в brokers.yaml & users.yaml

op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1037)
=> Change browser

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1038)
=> Add new broker torgibiz

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1039)
=> Добавление конфигурации в brokers\users.yaml для брокера torgibiz

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1040)
=> Add brokers polissya, agropromysl

op_robot_tests/tests_files/brokers/openprocurement_client.robot, op_robot_tests/tests_files/service_keywords.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/449)
=> Add getting amount keywords

op_robot_tests/tests_files/contract_signing.robot, op_robot_tests/tests_files/keywords.robot, op_robot_tests/tests_files/qualification.robot
Additionally, synchronization has been removed, as it is already included in the next test case
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/448)
=> Check active.awarded status

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1041)
=> Add new brokers to buildout

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1042)
=> add ubase broker to buildout

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1043)
=> Добавление конфигурации в brokers\users.yaml для брокера ubase

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1044)
=> Add new broker Rwsbank

buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1048)
=> add agrobirga broker to buildout

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
…rs.yaml)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1047)
=> Додавання інформації щодо майданчика agrobirga у brokers\users.yaml

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
Reverts openprocurement/robot_tests#1049
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1051)
=> Revert "Update uap data in brokers/users.yaml"

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1055)
=> Added uap data into brokers/users.yaml

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1056)
=> Changed accelerator

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1057)
=> accelerator: 180

op_robot_tests/tests_files/data/brokers.yaml
Because!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1058)
=> and again 180, in another way

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1059)
=> accelerator: 90

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1060)
=> accelerator for auctions: 1440

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1061)
=> [80, 30] for uap auctions

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1062)
=> accelerator 1440

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1063)
=> auction: [20,19]

op_robot_tests/tests_files/data/brokers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1064)
=> auctions 40, 30

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1066)
=> Додавання даних майданчика ubase у brokers\users.yaml

buildout.cfg, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1068)
=> Добавление нового брокера (thetender)

buildout.cfg, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1069)
=> Добавление данных брокера torgibiz

buildout.cfg, op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1073)
=> Update buildout.cfg, brokers.yaml and users.yaml for rwsbank

op_robot_tests/tests_files/data/brokers.yaml, op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1074)
=> Update brokers.yaml and users.yaml for centrex

buildout.cfg, op_robot_tests/tests_files/data/brokers.yaml
Broker configuration request
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1075)
=> Decreased accelerator for lot from 100 to 70 for centrex broker in brokers.yaml

op_robot_tests/tests_files/data/users.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/robot_tests/1076)
=> Changed homepage for centrex in users.yaml
